[programs.localnet]
permissionless_verifiable_registry = "govHvVVCZsdJLynaFJdqEWBU9AbJ4aHYdZsWno114V9"
permissionless_verifiable_schema_registry = "tkJqbNU3dk3eCwtT4EjSFisxza8JcuKSbDNbTZDQv76"

[permissionless_verifiable_registry]
url = "https://github.com/cardinal-consensus/spl-governance-registry"

[permissionless_verifiable_schema_registry]
url = "https://github.com/cardinal-consensus/spl-governance-registry"

[provider]
cluster = "localnet"
wallet = "/Users/jbogle/.config/solana/id.json"

[scripts]
test = "ts-mocha -p tests/tsconfig.json -t 1000000 tests/"
