[programs.localnet]
permissionless_verifiable_registry = "govHvVVCZsdJLynaFJdqEWBU9AbJ4aHYdZsWno114V9"

[permissionless_verifiable_registry]
url = "https://github.com/cardinal-consensus/spl-governance-registry"

[provider]
cluster = "localnet"
wallet = "/Users/jbogle/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
